repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
        - id: trailing-whitespace
        - id: detect-private-key
        - id: check-docstring-first
        - id: end-of-file-fixer
        - id: check-yaml
          args: [--unsafe]
        - id: check-added-large-files
        - id: requirements-txt-fixer
        - id: name-tests-test
          args: [--pytest-test-first]
  # - repo: https://github.com/psf/black-pre-commit-mirror
  #   rev: 24.8.0
  #   hooks:
  #       - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
        - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((homeassistant|script|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=hass,alot,datas,dof,dur,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args:
          - --pretty
          - --show-error-codes
          - --show-error-context